name: 'Download File To Workspace'
description: 'Download a file from the internet into the workspace.'
author: 'Carlos Pereira Atencio'
branding:
  icon: 'download-cloud'
  color: 'blue'
inputs:
  file-url:
    description: 'https://prx.vxload.com/file/dfac85f4aa6a70ef/WoWhWaDi70JP.part1.rar'
    required: true
  file-name:
    description: 'New filename to rename the downloaded file'
    required: false
  location:
    description: 'Path to download the file'
    required: false
    default: "."
outputs:
  file-path:
    description: 'The full path to the downloaded file'
runs:
  using: 'node12'
  main: 'dist/index.js'
